### 作业 3：矩阵操作与数据分析

#### 要求

1. **数组创建**：创建一个形状为 `(10， 10)` 的 NumPy 数组，命名为 `data_matrix`，使其包含从 0 到 99 的连续整数。
   - 应使用 `numpy.arange` 和 `numpy.reshape` 方法完成。

2. **子矩阵提取**：从 `data_matrix` 中提取出位于中心的 `4x4` 子矩阵。

3. **条件筛选与赋值**：
   - 在 `data_matrix` 中定位所有数值大于 75 的元素。
   - 使用布尔索引（Boolean Indexing）将这些元素的值全部重置为 0。此操作禁止使用任何形式的显式循环。

4. **向量化运算**：对上一步处理后的 `data_matrix` 进行整体缩放，将矩阵中的所有元素乘以 `0.8`。此操作应直接在原数组上（in-place）完成。

5. **数据聚合与定位**：
   - 找出最终矩阵中的最大值。
   - 确定该最大值在矩阵中的行和列索引。
   - **提示**：可结合使用 `numpy.argmax` 和 `numpy.unravel_index` 来高效完成定位。

In [105]:
import numpy as np

In [106]:
data_matrix = np.arange(100).reshape((10,10)).astype(float)

data_matrix

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [107]:
data_matrix[3:7, 3:7]

array([[33., 34., 35., 36.],
       [43., 44., 45., 46.],
       [53., 54., 55., 56.],
       [63., 64., 65., 66.]])

In [108]:
data_matrix[data_matrix > 75]

array([76., 77., 78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88.,
       89., 90., 91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [109]:
data_matrix[data_matrix > 75] = 0
data_matrix

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [110]:
# data_matrix = data_matrix.astype(np.float32, copy=False)
data_matrix *= 0.8
data_matrix

array([[ 0. ,  0.8,  1.6,  2.4,  3.2,  4. ,  4.8,  5.6,  6.4,  7.2],
       [ 8. ,  8.8,  9.6, 10.4, 11.2, 12. , 12.8, 13.6, 14.4, 15.2],
       [16. , 16.8, 17.6, 18.4, 19.2, 20. , 20.8, 21.6, 22.4, 23.2],
       [24. , 24.8, 25.6, 26.4, 27.2, 28. , 28.8, 29.6, 30.4, 31.2],
       [32. , 32.8, 33.6, 34.4, 35.2, 36. , 36.8, 37.6, 38.4, 39.2],
       [40. , 40.8, 41.6, 42.4, 43.2, 44. , 44.8, 45.6, 46.4, 47.2],
       [48. , 48.8, 49.6, 50.4, 51.2, 52. , 52.8, 53.6, 54.4, 55.2],
       [56. , 56.8, 57.6, 58.4, 59.2, 60. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ]])

In [111]:
idx = np.argmax(data_matrix)  # pyright: ignore[reportUnknownArgumentType, reportUnboundVariable]
print(np.unravel_index(idx, data_matrix.shape))  # pyright: ignore[reportUnknownMemberType, reportUnknownArgumentType, reportAttributeAccessIssue, reportUnboundVariable]

(np.int64(7), np.int64(5))


### 作业 4：广播机制与向量化距离计算

**目标**：考察对 NumPy 核心特性——广播（Broadcasting）机制的理解与应用，以实现高效的向量化计算。

#### 要求

1. **数据生成**：
   - 创建数组 `points_A`，形状为 `(5， 2)`，代表 5 个点的二维坐标。
   - 创建数组 `points_B`，形状为 `(8， 2)`，代表另外 8 个点的二维坐标。
   - 两个数组的数据均使用 `numpy.random.randint` 在 `[0， 100]` 区间内随机生成。

2. **距离矩阵计算**：
   - 计算 `points_A` 中每个点到 `points_B` 中每个点的欧几里得距离，最终生成一个形状为 `(5， 8)` 的距离矩阵 `distance_matrix`。
   - `distance_matrix[i， j]` 应表示 `points_A[i]` 与 `points_B[j]` 之间的距离。
   - **核心要求**：此过程严禁使用任何形式的显式 `for` 或 `while` 循环。必须利用 NumPy 的广播机制完成。
   - **提示**：考虑使用 `numpy.newaxis` 或 `numpy.reshape` 调整数组维度以触发广播。欧几里得距离公式为 $\\sqrt{\\sum(p_i - q_i)^2}$。

3. **轴向数据聚合**：
   - 对于 `points_A` 中的每一个点，从 `distance_matrix` 中找出其与 `points_B` 中所有点的最小距离。
   - 结果应为一个长度为 5 的一维数组。
   - **提示**：研究 `numpy.min` 函数的 `axis` 参数。

4. **复合条件查询**：
   - 找出 `points_B` 中，与 `points_A` 中**至少一个点**的距离小于 20 的所有点的**索引**。
   - **提示**：综合运用布尔掩码、`numpy.any` 以及 `numpy.where`。

In [112]:
np.random.seed(42)
points_A = np.random.randint(0, 101, size=(5, 2))
points_B = np.random.randint(0, 101, size=(8, 2))
points_A, points_B

(array([[51, 92],
        [14, 71],
        [60, 20],
        [82, 86],
        [74, 74]]),
 array([[87, 99],
        [23,  2],
        [21, 52],
        [ 1, 87],
        [29, 37],
        [ 1, 63],
        [59, 20],
        [32, 75]]))

In [ ]:
diff = points_A[:, np.newaxis, :] - points_B[np.newaxis, :, :]
distance_matrix = np.sqrt(np.sum(np.pow(diff, 2), axis=2))  # pyright: ignore[reportAny]
distance_matrix

array([[ 36.67424164,  94.25497334,  50.        ,  50.24937811,
         59.23681288,  57.80138407,  72.44308111,  25.49509757],
       [ 78.18567644,  69.58448103,  20.24845673,  20.61552813,
         37.16180835,  15.26433752,  68.01470429,  18.43908891],
       [ 83.48652586,  41.14608122,  50.44799302,  89.27485648,
         35.35533906,  73.00684899,   1.        ,  61.7170965 ],
       [ 13.92838828, 102.6498904 ,  69.83552105,  81.0061726 ,
         72.18032973,  84.20213774,  69.89277502,  51.19570294],
       [ 28.17800561,  88.23264702,  57.38466694,  74.14849965,
         58.25804665,  73.8241153 ,  56.04462508,  42.01190308]])

In [ ]:
np.min(distance_matrix, axis=1)   # pyright: ignore[reportAny]

array([25.49509757, 15.26433752,  1.        , 13.92838828, 28.17800561])

In [116]:
np.where(np.any(distance_matrix < 20, axis=0))

(array([0, 5, 6, 7]),)